name: 'fintech_analytics'
version: '1.0.0'
config-version: 2

profile: 'fintech_analytics'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

vars:
  # Keep in sync with terraform/finops's budget_amount variable
  finops_monthly_budget_eur: 5

models:
  fintech_analytics:
    staging:
      +materialized: view
    intermediate:
      +materialized: view
    marts:
      +materialized: table
    finops:
      +materialized: table
